[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevka-custom.variants.design]
at = "fourfold"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.iosevka-custom.ligations]
inherits = "dlig"
enables = ["exeqeq", "eqeqeq", "llggeq"]
